# Site settings
title: Notes to self on ruby and software engineering
email: emrebasala@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about ruby and software engineering, code examples and ideas about how to write better code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/emre-basala" # the base hostname & protocol for your site
twitter_username: emrebasala
github_username:  emre-basala
linkedin_url: https://www.linkedin.com/pub/emre-basala/63/3a8/814

# Build settings
markdown: redcarpet
